# Generated by Django 4.2.6 on 2025-12-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contatti.informazionibase')),
            ],
        ),
    ]
