# Generated by Django 4.2.6 on 2025-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_info',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
