# Generated by Django 4.2.6 on 2025-12-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatiPersonali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('data_nascita', models.DateField()),
                ('indirizzo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sito_web', models.URLField(null=True)),
                ('foto', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Referenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('posizione', models.CharField(max_length=255)),
                ('azienda', models.CharField(max_length=255)),
                ('contatto', models.CharField(max_length=255)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('link', models.URLField(null=True)),
                ('data_completamento', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=100)),
                ('livello', models.CharField(max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='Istruzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istituzione', models.CharField(max_length=255)),
                ('corso_di_studi', models.CharField(max_length=255)),
                ('titolo_conseguito', models.CharField(max_length=255)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('voto_finale', models.CharField(max_length=50, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_informazione', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='EsperienzaLavorativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('azienda', models.CharField(max_length=255)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(null=True)),
                ('descrizione', models.TextField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='Competenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competenza', models.CharField(max_length=255)),
                ('livello', models.CharField(max_length=50)),
                ('certificazioni', models.TextField(null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
        migrations.CreateModel(
            name='Certificazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_conseguimento', models.DateField()),
                ('ente_rilasciante', models.CharField(max_length=255)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datipersonali')),
            ],
        ),
    ]
