# Generated by Django 4.2.6 on 2025-12-10 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datipersonali',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datipersonali',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profili/'),
        ),
        migrations.AlterField(
            model_name='datipersonali',
            name='sito_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
