# Generated by Django 6.0 on 2025-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_datipersonali_user_alter_datipersonali_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperienzalavorativa',
            name='data_fine',
            field=models.DateField(blank=True, null=True),
        ),
    ]
