# Generated by Django 6.0 on 2025-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_esperienzalavorativa_data_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenza',
            name='certificazioni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='istruzione',
            name='voto_finale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progetto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
