# Generated by Django 5.2.8 on 2025-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenti",
            name="cognome",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
