# Generated by Django 4.2.6 on 2025-12-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformazioniBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('indirizzo', models.CharField(max_length=150)),
            ],
        ),
    ]
