# Generated by Django 4.2.6 on 2025-12-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('requisiti', models.TextField()),
                ('stipendio', models.CharField(max_length=50)),
                ('localita', models.CharField(max_length=255)),
                ('tipo_contratto', models.CharField(max_length=100)),
                ('data_pubblicazione', models.DateField(auto_now_add=True)),
                ('data_scadenza', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(max_length=255)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('partita_iva', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('descrizione', models.TextField()),
                ('sito_web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente_id', models.IntegerField()),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('stato', models.TextField()),
                ('messaggio', models.TextField()),
                ('annuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.annuncio')),
            ],
        ),
        migrations.AddField(
            model_name='annuncio',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.azienda'),
        ),
    ]
